services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres          
      POSTGRES_PASSWORD: 1234          
      POSTGRES_DB: gainge_assignment   
    ports:
      - "5432:5432"                   
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  app:
    build: .
    container_name: gainge-assignment-back
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: gainge_assignment

volumes:
  postgres_data: